language: cpp

sudo: required

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

before_install:
  - echo $CXX
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install gtkmm3 curl < /dev/null ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -y install libgtkmm-3.0-dev libcurl4-openssl-dev ; fi

script:
  - mkdir build && cd build
  - cmake -G "Unix Makefiles" ..
  - cmake --build . --config Release
