os:
  - Visual Studio 2015

configuration:
  - Release

#cache:
#  - C:\msys64 -> appveyor.yml
#  - C:\msys64 -> build.bat

install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - build.bat setup

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - build.bat build